#
# Copyright (c) 2004-2014, Cray Inc.  (See LICENSE file for more details)
#


GEN_CFLAGS += -I$(MASSIVETHREADS_INCLUDE_DIR)
GEN_LFLAGS += -L$(MASSIVETHREADS_LIB_DIR) -Wl,-rpath -Wl,$(MASSIVETHREADS_LIB_DIR)

LIBS += -lmyth-native -ldl
